name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to destroy (dev or qa)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa

jobs:
  terraform-destroy:
    name: Destroy Terraform Resources in ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout Code
        uses: actions/checkout@v4

      # Шаг 2: Установка Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      # Шаг 3: Инициализация Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/${{ github.event.inputs.environment }}

      # Шаг 4: Terraform Destroy
      - name: Terraform Destroy
        env:
          TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        run: terraform destroy -auto-approve
        working-directory: ./environments/${{ github.event.inputs.environment }}